name: ldcpy
channels:
  - conda-forge
dependencies:
  - cartopy=0.18
  - netcdf4
  - pip
  - xarray
  - zfpy
  - xrft
  - cmocean
  - numpy
  - scipy
  - matplotlib-base
  - dask
  - intake-esm
  - cython
  - scikit-image
  - scikit-build
  - opencv=4.2.0
  - nc-time-axis
