name: ldcpy_dev
channels:
  - conda-forge
dependencies:
  - cartopy
  - netcdf4
  - pip
  - xarray
  - zfpy
  - xrft
  - cmocean
  - numpy
  - scipy
  - matplotlib
  - pip:
      - cartopy
  - pre-commit
  - setuptools
  - jupyterlab
  - jupyter_contrib_nbextensions
  - codecov
  - pytest
  - pytest-cov
  - zfpy
