name: ldcpy
channels:
  - conda-forge
dependencies:
  - cartopy
  - netcdf4
  - pip
  - xarray
  - zfpy
  - xrft
  - cmocean
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - pip:
      - cartopy
