name: ldcpy
channels:
  - conda-forge
dependencies:
  #  - python=*=*cp*
  - python=3.9
  - cartopy
  - cmocean
  - codecov
  - cython
  - dask
  - graphviz
  - intake-esm
  - notebook=6.4.12
  - jupyter_contrib_nbextensions
  - jupyterlab
  - matplotlib
  - matplotlib-base
  - netcdf4
  - numpy
  - opencv
  - pandas
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - scikit-image
  - scipy
  - setuptools
  - zfpy
  - cf_xarray
  - astropy
  - ipython
  - pooch
  - statsmodels
  - pip:
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/xarray-contrib/cf-xarray.git
      - git+https://github.com/xgcm/xrft.git
