name: ldcpy-docs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - cartopy
  - xarray
  - scipy
  - matplotlib
  - pip
  - pip:
      - sphinx=4.5.0
      - sphinx_rtd_theme=1.1.1
      - nbsphinx
      - sphinx-reload
      - pillow
      - ipython
      - -r ../requirements.txt
      - -e ..
