name: myenv
channels:
  - conda-forge
dependencies:
  - cartopy
  - cf_xarray
  - cmocean
  - dask
  - dask-gateway
  - dask-labextension
  - distributed
  - intake-esm
  - ipywidgets
  - jupyterlab>=3
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - nodejs
  - python=3.8
  - scikit-image
  - xarray
  - xrft
  - pip
  - pip:
      - -e ..
